### ISSUE TITLE
Plugin not working with mixin

### ISSUE THREAD

**Issue by SkeLLLa** [oscaroox/objection-timestamps#2]
Example:
```js
const {Model, mixin} = require('objection');
const Timestamps = require('objection-timestamps');
class MyModel extends mixin(Model, [Timestamps]) {
  static get tableName() {
    return 'myModel';
  }
}
```

Error:
```
TypeError: Class extends value Model => {
  return class extends Model {

    /**
     * Before insert.
     */

    $beforeInsert(c...<omitted>... } is not a constructor or null
  at timeStampModel (/app/node_modules/objection-timestamps/index.js:22:24)
  at module.exports (/app/node_modules/objection-timestamps/index.js:17:10)
  at mixins.reduce (/app/node_modules/objection/lib/utils/mixin.js:8:12)
  at Array.reduce (<anonymous>)
  at mixin (/app/node_modules/objection/lib/utils/mixin.js:7:17)
  at Object.<anonymous> (/app/models/Account.js:6:23)
  at Module._compile (module.js:660:30)
  at Object.Module._extensions..js (module.js:671:10)
  at Module.load (module.js:573:32)
  at tryModuleLoad (module.js:513:12)
  at Function.Module._load (module.js:505:3)
  at Module.require (module.js:604:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/app/models/UserProfile.js:5:17)
  at Module._compile (module.js:660:30)
  at Object.Module._extensions..js (module.js:671:10)
```

**Comment by oscaroox** [comment]
@SkeLLLa everything seems to work, i just created tests for the compose and mixin helper,
can you give more information?

**Comment by SkeLLLa** [comment]
Got the problem. Seems it was side-effect from other plugin that was connected prior to timestamp.

Sorry.
